### ISSUE TITLE
请问这个项目还有继续吗？

### ISSUE THREAD

**Issue by liho98** [summerness/arbitrage_binance#3]
请问这个项目还能不能盈利了呢？请问有微信群吗？

**Comment by summerness** [comment]
不做了，不赚钱。有套利点出来的时候，这边的交易速度怎么都不够快，应该交易所也在做这种套利
而且好像还有人专门做这种套利点来骗机器人的钱
我现在基本上不再做这个了
做量化交易需要大量资金才能保证盈利，我研究很久，没有那么多钱，所以也不再继续了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "summerness/arbitrage_binance"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月27日(星期天) 下午4:10
收件人:&nbsp;"summerness/arbitrage_binance"<arbitrage_binance@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[summerness/arbitrage_binance] 请问这个项目还有继续吗？ (#3)





 
请问这个项目还能不能盈利了呢？请问有微信群吗？
